version: '3'

services:
  web:
    build:
      context: .
      target: web
    container_name: recipe-service
    env_file:
      - .env
    # volumes:
    #   - .:/code
    develop:
      watch:
        - action: sync
          path: .
          target: /code/
    ports:
      - 2000:2000
    depends_on:
      - celery
  

  celery:
    build:
      context: .
      target: celery
    container_name: recipe-celery-service
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: .
          target: /code/