"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

ENVIRONMENT = os.environ.get("ENVIRONMENT", default="production" )

if ENVIRONMENT == 'production':
    SECURE_BROWSER_XSS_FILTER = True # protect against cross-site scripting attacks
    X_FRAME_OPTIONS = 'DENY' # to protect against clickjacking attacks
    SECURE_SSL_REDIRECT = True # make all non HTTPS traffic redirect  to HTTPS
    SECURE_HSTS_SECONDS = 3600 # [HTTP Strict Transfer Security] the time in seconds the browser should remember that this application is only accessible using HTTPS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True # to force every subdomain to be accessible over HTTPS only
    SECURE_HSTS_PRELOAD =  True # to ensure https connection to website, before actually visiting the website
    SECURE_CONTENT_TYPE_NOSNIFF = True # 
    SESSION_COOKIE_SECURE = True # to use session cookie only over HTTPS
    CSRF_COOKIE_SECURE = True # to secure csrf cookie in HTTPS connection
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') ## to prevent redirects

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-$&vhg-f)r%92=v1ngplqdq83&x0$(qbb#299**uks+pa2cg!9l'

SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get('DEBUG', default=0))

ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1', 'nutranova-recipe.onrender.com']




# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #local apps
    "recipes.apps.RecipesConfig",
    "file.apps.FileConfig",


    # 3rd party apps
    "ariadne_django",
    "cloudinary",
    "rest_framework",
    "channels"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = "core.asgi.application"


# configuration for websocket scalability with redis
# CHANNEL_LAYERS = {
#     "default": {
#         # "BACKEND": "asgi_redis.RedisChannelLayer",
#         "BACKEND": "channels_redis.core.RedisChannelLayer",

#         "CONFIG": {
#             # "hosts": [(os.environ.get('REDIS_SERVER_NAME'), 25289)],
#             "hosts": [("rediss://default:AVNS_13ADJ8_ZEdd-z9tg_oA@nutranova-recipe-redis-nutranovahealth.a.aivencloud.com:25289")],
#         },
#         # "ROUTING": "core.routing.websocket_urlpatterns",
#     },
# }

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",

        "CONFIG": {
            "hosts": [("rediss://default:AVNS_13ADJ8_ZEdd-z9tg_oA@nutranova-recipe-redis-nutranovahealth.a.aivencloud.com:25289")],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }


    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('AIVEN_DATABASE_NAME'),
        'USER': os.environ.get('AIVEN_USER'),
        'PASSWORD': os.environ.get('AIVEN_PASSWORD'),
        'HOST': os.environ.get('AIVEN_HOST'),
        'PORT': os.environ.get('AIVEN_PORT'),
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ENVIRONMENT = os.environ.get('ENVIRONMENT')

# cache session engine config for request session storage

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL")
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"