# Generated by Django 4.2.7 on 2023-11-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_chef_alter_recipe_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chef',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
