# Generated by Django 4.2.7 on 2023-11-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_chef_first_name_chef_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.URLField(default='', max_length=500),
        ),
    ]
