# Generated by Django 4.2.7 on 2023-11-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_thumbnail_recipe_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
