# Generated by Django 4.2.7 on 2023-12-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_thumbnail_alter_recipe_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
