# Generated by Django 4.2.7 on 2023-12-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='username',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
