# Generated by Django 4.2.7 on 2024-01-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='liker',
        ),
    ]
