# Generated by Django 4.2.7 on 2024-05-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='chef',
            new_name='writer',
        ),
    ]
