# Generated by Django 4.2.7 on 2024-05-13 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_comment_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upVotes', to='recipes.recipe')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.chef')),
            ],
        ),
        migrations.CreateModel(
            name='DownVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downVotes', to='recipes.recipe')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.chef')),
            ],
        ),
    ]
