# Generated by Django 4.2.7 on 2024-05-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_upvote_downvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chef',
            name='vote_strength',
            field=models.IntegerField(default=1),
        ),
    ]
