# Generated by Django 4.2.7 on 2024-06-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_chef_is_verified_chef_vote_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published')], db_index=True, default='DRAFT', max_length=10),
        ),
    ]
