# Generated by Django 4.2.7 on 2024-06-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_alter_recipe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='image',
            field=models.URLField(default='https://www.gravatar.com/avatar', max_length=500),
        ),
    ]
