"These are the choices for various units of ingredients measurements"
enum INGREDIENT_MEASUREMENT_UNITS{
  "Ounce"
  OZ
  "Pound"
  LB
  "Gram"
  G
  "Kilogram"
  KG
  "Tablespoon"
  TBSP
  "Teaspoon"
  TSP
  "Cup"
  C
  "Pint"
  PT
  "Gallon"
  GAL
  "Liter"
  L
  "Mililiter"
  ML
  "Dozen"
  DOZ
  "Quart"
  QT
  "Loaf"
  LOAF
  "Bar"
  BAR
  "Package"
  PACKAGE
  "Piece"
  PIECE
}

"Ingredient schema."
type Ingredients{
  name: String
  quantity: Int
  unit: String
}

"Ingredients inputted for recipe creation or modification would be following this schema"
input IngredientsInput{
  name: String!
  quantity: Int!
  unit: INGREDIENT_MEASUREMENT_UNITS
}

"Recipe status"
enum RECIPE_STATUS{
  DRAFT
  PUBLISHED
}

"Time input schema for cooking and preparation time"
input TimeInput{
  hour: Int
  minute: Int!
  seconds: Int
}

"Schema representing data body for recipe creation"
input CreateRecipeInput{
  title: String!
  description: String!
  ingredients: [IngredientsInput]!
  instructions: [String!]!
  preparation_time: TimeInput!
  cooking_time: TimeInput!
  servings: Int!
  images: [String]!
  tags: [String!]!
  video: String
  thumbnail: String
}

"Schema representing data body for recipe modification"
input EditRecipeInput{
  id: String!
  title: String
  description: String
  ingredients: [IngredientsInput]
  instructions: [String]
  preparation_time: TimeInput
  cooking_time: TimeInput
  servings: Int
  images: [String]
  tags: [String]
  video: String
  thumbnail: String
  status: RECIPE_STATUS
}

"Chef schema on response"
type Chef{
  username: String
  first_name: String
  last_name: String
}


"Schema type for recipe nutritional value"
type NutritionalValue{
  calories: String  # using String type because of the units attached to the numbers
  fat: String
  cholesterol: String
  sodium: String
  carbohydrates: String
  fiber: String
  sugar: String
  protein: String
  potassium: String
}

"Recipe schema on response"
type Recipe{
  id: Int
  title: String
  description: String
  ingredients: [Ingredients]
  instructions: [String]
  preparationTime: String
  cookingTime: String
  servings: Int
  images: [String]
  tags: [String]
  nutritionalValue: NutritionalValue
  video: String
  thumbnail: String
  chef: Chef
  status: RECIPE_STATUS
  created: String
  published: String
}


type Like{
  liker: Chef
  recipe: Recipe
}

"Response for single recipe mutation and query operation"
type RecipeResponse{
  message: String
  recipe: Recipe
  likes: Int
  error: String
}

type RecipeFeedResponse{
  message: String
  feed: [Recipe]
}

"The query resolvers"
type Query{
  recipeTags: [String]!
  recipeFeed: RecipeFeedResponse
  # singleRecipe(pk: Int): RecipeResponse
  myDrafts: [Recipe]
  myPublishedRecipes: [Recipe]
  draft(pk: Int): Recipe

}

"The mutation resolvers"
type Mutation{
  createRecipe(input: CreateRecipeInput): RecipeResponse
  editRecipe(input: EditRecipeInput): RecipeResponse
  likeRecipe(pk: Int): String
  unLikeRecipe(pk: Int): String
  deleteRecipe(pk: Int): String
}

type Subscription{
  singleRecipe(pk: Int): RecipeResponse
}
