enum INGREDIENT_MEASUREMENT_UNITS{
  oz
  lb
  g
  kg
  Tbsp
  tsp
  c
  pt
  gal
  l
  mL
  doz
  qt
  loaf
  bar
  package
  piece
}

type Ingredients{
  name: String
  quantity: Int
  unit: String
}

input IngredientsInput{
  name: String!
  quantity: Int!
  unit: INGREDIENT_MEASUREMENT_UNITS
}

enum RECIPE_STATUS{
  DRAFT
  PUBLISHED
}

input TimeInput{
  hour: Int
  minute: Int!
  seconds: Int
}


input CreateRecipeInput{
  title: String!
  description: String!
  ingredients: [IngredientsInput]!
  instructions: [String!]!
  preparation_time: TimeInput!
  cooking_time: TimeInput!
  servings: Int!
  images: [String]!
  tags: [String!]!
  video: String
  thumbnail: String
}


type Chef{
  username: String
  first_name: String
  last_name: String
}


type NutritionalValue{
  calories: String  # using String type because of the units attached to the numbers
  fat: String
  cholesterol: String
  sodium: String
  carbohydrates: String
  fiber: String
  sugar: String
  protein: String
  potassium: String
}


type Recipe{
  title: String
  description: String
  ingredients: [Ingredients]
  instructions: [String]
  preparationTime: String
  cookingTime: String
  servings: Int
  images: [String]
  tags: [String]
  nutritionalValue: NutritionalValue
  video: String
  thumbnail: String
  chef: Chef
  status: RECIPE_STATUS
  created: String
  published: String
}

type RecipeResponse{
  message: String
  recipe: Recipe
  error: String
}



type Query{
  recipeTags: [String]!
}

type Mutation{
  createRecipe(input: CreateRecipeInput): RecipeResponse
}